### ISSUE TITLE
Cannot find *_cropped.png images?

### ISSUE THREAD

**Issue by Soledad89** [carpedm20/simulated-unsupervised-tensorflow#3]
How to get the *_cropped.png images? Thanks a lot.

**Comment by carpedm20** [comment]
gaze_data.py ([here](https://github.com/carpedm20/simulated-unsupervised-tensorflow/blob/master/data/gaze_data.py#L89)) automatically detect whether there are *_cropped.png or not. If there are no enough *_cropped.png, then the code will generate them.

**Comment by Soledad89** [comment]
Okay, I Got it. Thanks sooo much @carpedm20 .
